import os
import pandas as pd

class CASME2DataParser:
    def __init__(self, mapping_file, aligned_rgb_dir, emotion_map):
        """
        mapping_file: path to 'casme2_clean_labels.csv' generated by preprocess_casme2.py
        aligned_rgb_dir: path to 'casme2_aligned_rgb'
        emotion_map: e.g., {'positive': 0, 'negative': 1, 'surprise': 2}
        """
        self.mapping_file = mapping_file
        self.aligned_rgb_dir = aligned_rgb_dir
        self.emotion_map = emotion_map
        self.samples = []
        self._parse_data()

    def _parse_data(self):
        if not os.path.exists(self.mapping_file):
            print(f"Error: mapping file {self.mapping_file} not found.")
            return

        df = pd.read_csv(self.mapping_file)

        for index, row in df.iterrows():
            subject = str(row['subject']).zfill(2)
            seq_name = str(row['sequence'])
            emotion_clean = str(row['emotion'])

            if emotion_clean not in self.emotion_map:
                continue

            label = self.emotion_map[emotion_clean]

            sequence_path = os.path.join(self.aligned_rgb_dir, subject, seq_name)

            if not os.path.exists(sequence_path):
                print(f"Warning: Aligned sequence path does not exist: {sequence_path}")
                continue

            image_files = [f for f in os.listdir(sequence_path) if f.endswith('.jpg')]
            if not image_files:
                continue

            image_files.sort()

            sample = {
                'subject': subject,
                'video_name': seq_name,
                'aligned_path': sequence_path,
                'image_files': image_files,
                'num_frames': len(image_files),
                'label': label,
                'emotion': emotion_clean
            }
            self.samples.append(sample)

    def get_samples(self):
        return self.samples

    def get_all_subjects(self):
        return sorted(list(set(s['subject'] for s in self.samples)))

if __name__ == '__main__':
    mapping_file = 'casme2_aligned_rgb/casme2_clean_labels.csv'
    video_dir = 'casme2_aligned_rgb'

    emotion_map = {
        'positive': 0,
        'negative': 1,
        'surprise': 2
    }

    if os.path.exists(mapping_file):
        parser = CASME2DataParser(mapping_file, video_dir, emotion_map)
        print(f"Found {len(parser.get_samples())} samples.")
        print(f"Subjects: {parser.get_all_subjects()}")
    else:
        print("Mapping file not found")
