import os
import pandas as pd

class SAMMDataParser:
    def __init__(self, mapping_file, aligned_rgb_dir, emotion_map):
        """
        mapping_file: path to 'samm_clean_labels.csv' generated by preprocess_samm.py
        aligned_rgb_dir: path to 'samm_aligned_rgb'
        emotion_map: e.g., {'positive': 0, 'negative': 1, 'surprise': 2}
        """
        self.mapping_file = mapping_file
        self.aligned_rgb_dir = aligned_rgb_dir
        self.emotion_map = emotion_map
        self.samples = []
        self._parse_data()

    def _parse_data(self):
        if not os.path.exists(self.mapping_file):
            print(f"Error: mapping file {self.mapping_file} not found.")
            return

        df = pd.read_csv(self.mapping_file)
        
        for index, row in df.iterrows():
            subject = str(row['subject']).zfill(3)
            seq_name = str(row['sequence'])
            emotion_clean = str(row['emotion']) # 'positive', 'negative', 'surprise'
            
            if emotion_clean not in self.emotion_map:
                continue
                
            label = self.emotion_map[emotion_clean]
            
            sequence_path = os.path.join(self.aligned_rgb_dir, subject, seq_name)
            
            if not os.path.exists(sequence_path):
                print(f"Warning: Aligned sequence path does not exist: {sequence_path}")
                continue
                
            # 获取该序列中的所有预处理图片文件 (.jpg)
            image_files = [f for f in os.listdir(sequence_path) if f.endswith('.jpg')]
            if not image_files:
                continue
                
            # 按文件名排序确保顺序正确
            image_files.sort()

            sample = {
                'subject': subject,
                'video_name': seq_name,
                'aligned_path': sequence_path,
                'image_files': image_files,
                'num_frames': len(image_files),
                'label': label,
                'emotion': emotion_clean
            }
            self.samples.append(sample)

    def get_samples(self):
        return self.samples

    def get_all_subjects(self):
        return sorted(list(set(s['subject'] for s in self.samples)))

if __name__ == '__main__':
    # Test code
    mapping_file = 'samm_clean_labels.csv'
    video_dir = 'samm_aligned_rgb'
    
    emotion_map = {
        'positive': 0,
        'negative': 1,
        'surprise': 2
    }
    
    if os.path.exists(mapping_file):
        parser = SAMMDataParser(mapping_file, video_dir, emotion_map)
        print(f"Found {len(parser.get_samples())} samples.")
        print(f"Subjects: {parser.get_all_subjects()}")
    else:
        print("Mapping file not found")
